# Generated by Django 5.0.6 on 2024-10-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spl_discoveries', '0003_alter_appointment_when_scheduled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='customers_request',
        ),
        migrations.AddField(
            model_name='appointment',
            name='when_completed',
            field=models.DateTimeField(blank=True, help_text='The date and time the appointment was done', null=True, verbose_name='when completed'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customers_availability',
            field=models.CharField(blank=True, help_text="The customer's preference regarding scheduling", max_length=255, verbose_name="customer's availability"),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='request_summary',
            field=models.CharField(blank=True, help_text="A summary of the customer's request", max_length=255, verbose_name='request summary'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='when_scheduled',
            field=models.DateTimeField(blank=True, help_text='The date and time the appointment is scheduled', null=True, verbose_name='when scheduled'),
        ),
    ]
