# Generated by Django 5.0.6 on 2024-11-26 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spl_discoveries', '0007_rename_full_name_inquiry_name_full_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='honeypot',
        ),
    ]
