# Generated by Django 5.0.6 on 2024-12-05 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spl_discoveries', '0008_remove_inquiry_honeypot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('when_scheduled', 'date_submitted')},
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ('date_submitted',)},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='when_submitted',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='when_submitted',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date_submitted',
            field=models.DateField(blank=True, help_text='The date that the customer submitted the request', null=True, verbose_name='date submitted'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='date_submitted',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='The date that the customer submitted the request', null=True, verbose_name='date submitted'),
        ),
    ]
