# Generated by Django 5.0.6 on 2024-12-06 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spl_discoveries', '0009_alter_appointment_options_alter_inquiry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Inquiry',
            field=models.ForeignKey(blank=True, help_text='The inquiry upon which this appointment is based', null=True, on_delete=django.db.models.deletion.SET_NULL, to='spl_discoveries.inquiry'),
        ),
    ]
